# This workflow builds and pushes a Docker image for a canary feature deployment.
name: Canary Feature Deployment

# Configures workflow to be manually triggered with optional experiment name input
on:
  workflow_dispatch:
    inputs:
      experiment_name:
        description: 'Optional: Custom name for this experiment/feature tag (e.g., "new-sentiment-model"). If empty, the branch name will be used.'
        required: false
        type: string

# Sets environment variables for Docker image naming and tagging
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
  CANARY_TAG: canary # The stable tag for your experimental deployment slot
  GIT_USER_NAME: "github-actions[bot]"
  GIT_USER_EMAIL: "github-actions[bot]@users.noreply.github.com"

# Grants permissions needed for package registry operations
permissions:
  contents: write
  packages: write

jobs:
  build-and-push-canary:
    runs-on: ubuntu-latest

    steps:
    # Determines the feature tag name from input or branch name with sanitization
    - name: Determine Feature Tag Name
      id: feature_tag_name
      run: |
        INPUT_NAME="${{ github.event.inputs.experiment_name }}"
        BRANCH_NAME="${{ github.ref_name }}"

        if [ -n "$INPUT_NAME" ]; then
          RAW_NAME="$INPUT_NAME"
        else
          RAW_NAME="$BRANCH_NAME"
        fi

        # Sanitize the raw name (remove refs/heads/, replace slashes, etc.)
        SANITIZED_NAME=$(echo "$RAW_NAME" | sed 's#refs/heads/##g' | tr -s '/' '-' | sed 's/[^a-zA-Z0-9._-]/-/g' | sed 's/^-*//;s/-*$//')
        # Ensure it's not empty after sanitization, default to 'feature' if it is
        if [ -z "$SANITIZED_NAME" ]; then
          SANITIZED_NAME="feature"
        fi
        echo "feature_tag=${SANITIZED_NAME}" >> $GITHUB_OUTPUT
        echo "Determined feature tag: ${SANITIZED_NAME}"
    
    # Creates the version tag name to be used in multiple steps
    - name: Set Version Tag
      id: version_tag
      run: |
        VERSION_TAG="version.beta-${{ steps.feature_tag_name.outputs.feature_tag }}"
        echo "tag=${VERSION_TAG}" >> $GITHUB_OUTPUT
        echo "Created version tag: ${VERSION_TAG}"

    # Checks out the repository code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Sets up QEMU for multi-architecture container builds
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Configures Docker Buildx for multi-platform image builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Creates metadata for Docker image including feature-specific tags
    - name: Generate image metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ steps.feature_tag_name.outputs.feature_tag }}
          type=raw,value=${{ env.CANARY_TAG }}
        flavor: |
          latest=false

    # Authenticates with GitHub Container Registry
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Builds and pushes the feature-specific Docker image with canary tags
    - name: Build & push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . 
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          NEXT_PUBLIC_APP_VERSION="${{ steps.version_tag.outputs.tag }}"
        cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max,image-manifest=true
        
    # Creates a Git tag for this feature branch with a matching version format
    - name: Create Git tag for feature branch
      run: |
        git config user.name "${{ env.GIT_USER_NAME }}"
        git config user.email "${{ env.GIT_USER_EMAIL }}"
        echo "Creating tag: ${{ steps.version_tag.outputs.tag }}"
        git tag -a "${{ steps.version_tag.outputs.tag }}" -m "Canary feature deployment for ${{ steps.feature_tag_name.outputs.feature_tag }}"
        git push origin "${{ steps.version_tag.outputs.tag }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Outputs information about the built and pushed images for reference
    - name: Output image tags
      run: |
        echo "Pushed image with tags: ${{ steps.meta.outputs.tags }}"
        echo "-------------------------------------------------------------------------"
        echo "Image for this specific feature/experiment: ${{ env.IMAGE_NAME }}:${{ steps.feature_tag_name.outputs.feature_tag }}"
        echo "Image for the canary deployment slot:       ${{ env.IMAGE_NAME }}:${{ env.CANARY_TAG }}"
        echo "-------------------------------------------------------------------------"
        echo "Update your Kubernetes experimental deployment to use: ${{ env.IMAGE_NAME }}:${{ env.CANARY_TAG }}"
        echo "Version tag created: ${{ steps.version_tag.outputs.tag }}"