name: Continuous Deployment

on:
  push:
    branches: [3-cicd-workflow]        
    tags:     ['v*.*.*']
  # For testing purposes, you can trigger the workflow manually
  workflow_dispatch:

permissions:
  contents: write    
  packages:  write        

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get current version
      id: get_version
      if: github.ref == 'refs/heads/3-cicd-workflow'
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_prerelease_bump: false      
        default_bump: false
        tag_prefix: v

    - name: Resolve version
      id: version
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "value=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"
        else
          echo "value=${{ steps.get_version.outputs.new_version }}" >> "$GITHUB_OUTPUT"
        fi

    - name: Generate image metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
        tags: |
          type=raw,value=latest
          type=raw,value=${{ steps.version.outputs.value }}

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags:   ${{ steps.meta.outputs.tags }}

    - name: Bump patch and add pre tag
      id: bump_patch
      if: github.ref == 'refs/heads/3-cicd-workflow'
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pre_release_branches: 3-cicd-workflow
        default_prerelease_bump: prepatch      
        append_to_pre_release_tag: pre        
        tag_prefix: v
        default_bump: patch