name: Integration

on:
  pull_request:
    branches: [main]        

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint and format check
        run: |
          npm run lint

      # Enables the runner to emulate different architectures for the build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Creates a builder instance capable of multi-platform builds
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image for multi-architecture
        id: docker_build_validate
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
