name: Continuous Integration

on:
  pull_request:
  # For testing purposes, you can trigger the workflow manually
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Lint and Format Check
        run: |
          npm run lint

      # Enables the runner to emulate different architectures for the build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Creates a builder instance capable of multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for Multi-Platform (Validation Only)
        id: docker_build_validate
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
