name: Continuous Integration

on:
  pull_request:
  # For testing purposes, you can trigger the workflow manually
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
